# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0002_rename_longtitude_barangay_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], default='Active', max_length=15)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
            ],
            options={
                'db_table': 'tbl_sensor_nodes',
            },
        ),
        migrations.CreateModel(
            name='SystemHealthLog',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_voltage', models.FloatField()),
                ('signal_strength', models.FloatField()),
                ('sensor_continuity', models.BooleanField()),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode')),
            ],
            options={
                'db_table': 'tbl_system_health_logs',
            },
        ),
    ]
