# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0002_rename_node_systemhealthlog_node_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemhealthlog',
            old_name='node_id',
            new_name='node',
        ),
    ]
