# Generated by Django 5.2.14 on 2026-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0003_rename_node_id_systemhealthlog_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='node_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
