# Generated by Django 5.2.14 on 2026-06-16 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0004_sensornode_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornode',
            name='installed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=15),
        ),
    ]
