# Generated by Django 5.2.14 on 2026-06-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0009_sensornode_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensornode',
            name='canal_shape',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='canal_width',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='sensor_height',
        ),
    ]
