# Generated by Django 5.2.14 on 2026-06-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
        ('sensor_nodes', '0010_remove_sensornode_canal_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='canal_shape',
            field=models.CharField(choices=[('rectangular', 'Rectangular'), ('trapezoidal', 'Trapezoidal')], default='rectangular', help_text="Cross-sectional shape of the canal at this node's location.", max_length=20),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='canal_width',
            field=models.FloatField(blank=True, help_text="Width of canal in meters at this node's location. Measured once at installation.", null=True),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='sensor_height',
            field=models.FloatField(blank=True, help_text='Fixed distance in cm from camera/sensor mount to canal floor. Measured once at installation.', null=True),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='barangay',
            field=models.ForeignKey(blank=True, db_column='barangay_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangay.barangay'),
        ),
    ]
