# Generated by Django 5.2.14 on 2026-06-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0011_sensornode_canal_shape_sensornode_canal_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensornode',
            name='canal_shape',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='canal_width',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='sensor_height',
        ),
    ]
