# Generated by Django 5.2.14 on 2026-07-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0012_remove_sensornode_canal_shape_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensornode',
            old_name='status',
            new_name='device_status',
        ),
    ]
