# Generated by Django 5.2.14 on 2026-07-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0013_rename_status_sensornode_device_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensornode',
            old_name='device_status',
            new_name='status',
        ),
    ]
