# Generated by Django 5.2.14 on 2026-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0014_rename_device_status_sensornode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='device_key_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
