# Generated by Django 5.2.14 on 2026-09-11 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0015_sensornode_device_key_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(db_column='marked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode')),
            ],
            options={
                'db_table': 'tbl_maintenance_logs',
            },
        ),
    ]
