# Generated by Django 5.2.14 on 2026-09-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0016_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='device_model',
            field=models.CharField(blank=True, default='ESP32-S3 + SIM7600 (4G) + HC-SR04 + OV2640 Camera', max_length=150),
        ),
    ]
