# Generated by Django 5.2.14 on 2026-09-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0017_sensornode_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealthlog',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
