# Generated by Django 5.2.14 on 2026-09-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
        ('hotspots', '0010_alter_hotspot_canal_shape'),
        ('sensor_nodes', '0019_sensornode_forced_sleep_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAssignmentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotspot_name', models.CharField(blank=True, default='', max_length=150)),
                ('barangay_name', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Reassigned', 'Reassigned'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], max_length=15, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(blank=True, db_column='barangay_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangay.barangay')),
                ('ended_by', models.ForeignKey(blank=True, db_column='ended_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_assignments_ended', to=settings.AUTH_USER_MODEL)),
                ('hotspot', models.ForeignKey(blank=True, db_column='hotspot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='hotspots.hotspot')),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='sensor_nodes.sensornode')),
            ],
            options={
                'db_table': 'tbl_node_assignment_history',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['node', '-started_at'], name='tbl_node_as_node_id_242cb4_idx'), models.Index(fields=['hotspot', '-started_at'], name='tbl_node_as_hotspot_d2f3d1_idx')],
            },
        ),
    ]
