# Generated by Django 5.2.14 on 2026-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_nodes', '0021_seed_node_assignment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Retired', 'Retired')], help_text='Why the log was closed — Fixed (normal repair) or Retired (node taken out of service before repair finished). Null while still open.', max_length=10, null=True),
        ),
    ]
