"use client"

import { createPortal } from "react-dom"

type PrintReportProps = {
  reportTitle: string
  columns: string[]
  rows: (string | number)[][]
  generatedBy: string
}

export function PrintReport({ reportTitle, columns, rows, generatedBy }: PrintReportProps) {
  if (typeof document === "undefined") return null

  const generatedAt = new Date().toLocaleString('en-PH', {
    month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  const content = (
    <div className="print-report">
      <div className="print-header">
        <img src="/ROS-logo.jpg" className="print-logo" alt="" />
        <div className="print-header-text">
          <p>Republic of the Philippines</p>
          <p>Province of La Union</p>
          <p className="print-municipality">Municipality Of Rosario</p>
        </div>
      </div>
      <div className="print-divider" />
      <div className="print-title-block">
        <p className="print-office">{reportTitle}</p>
        <p className="print-meta">
          Generated by <span className="print-generated-by">{generatedBy}</span>
          &nbsp;|&nbsp; {generatedAt} &nbsp;|&nbsp; {rows.length} records
        </p>
      </div>
      <table className="print-table">
        <thead>
          <tr>{columns.map(c => <th key={c}>{c}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>
          ))}
        </tbody>
      </table>
      <div className="print-footer">AGOS — Automated Geo-Based Obstruction Sensing System</div>
    </div>
  )

  return createPortal(content, document.body)
}