name: Build Android Preview

on:
  push:
    branches: ['mobile-build']
    paths: ['mobile/**']

jobs:
  android_preview_build:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview