# Generated by Django 5.2.14 on 2026-06-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('hotspot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
            ],
            options={
                'db_table': 'tbl_hotspots',
                'unique_together': {('barangay', 'name')},
            },
        ),
    ]
