# Generated by Django 5.2.14 on 2026-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='description',
            field=models.TextField(),
        ),
    ]
