# Generated by Django 5.2.14 on 2026-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_alter_hotspot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='canal_shape',
            field=models.CharField(choices=[('rectangular', 'Rectangular'), ('trapezoidal', 'Trapezoidal')], default='rectangular', help_text='Cross-sectional shape of the canal at this location.', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='canal_width',
            field=models.FloatField(blank=True, help_text='Width of canal in meters at this location.', null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='sensor_height',
            field=models.FloatField(blank=True, help_text='Fixed distance in cm from sensor/camera mount to canal floor. Measured once at installation.', null=True),
        ),
    ]
