# Generated by Django 5.2.14 on 2026-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_hotspot_canal_shape_hotspot_canal_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
