# Generated by Django 5.2.14 on 2026-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0004_hotspot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
