# Generated by Django 5.2.14 on 2026-07-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0005_hotspot_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='code',
            new_name='hotspot_code',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='description',
            new_name='landmark_desc',
        ),
    ]
