# Generated by Django 5.2.14 on 2026-07-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0006_rename_code_hotspot_hotspot_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='landmark_desc',
            new_name='description',
        ),
    ]
