# Generated by Django 5.2.14 on 2026-07-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0007_rename_landmark_desc_hotspot_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='hotspot_code',
            new_name='code',
        ),
    ]
