# Generated by Django 5.2.14 on 2026-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0008_rename_hotspot_code_hotspot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='canal_depth',
            field=models.FloatField(blank=True, help_text='Registered depth in cm of the canal at this hotspot, used for water-level percentage classification (Normal/Warning/Critical). Distinct from sensor_height.', null=True),
        ),
    ]
