# Generated by Django 5.2.14 on 2026-08-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0009_hotspot_canal_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='canal_shape',
            field=models.CharField(choices=[('rectangular', 'Rectangular'), ('trapezoidal', 'Trapezoidal'), ('circular', 'Circular')], default='rectangular', help_text='Cross-sectional shape of the canal at this location.', max_length=20),
        ),
    ]
