# Generated by Django 5.2.14 on 2026-09-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('signatory_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('Barangay Secretary', 'Barangay Secretary'), ('Chairman Environment', 'Chairman Environment'), ('Brgy. Sanitary Inspector', 'Brgy. Sanitary Inspector'), ('Punong Barangay', 'Punong Barangay')], max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='barangay.barangay')),
            ],
            options={
                'db_table': 'tbl_signatory',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('barangay', 'position'), name='unique_active_signatory_per_barangay_position')],
            },
        ),
    ]
