import React, { useState } from "react";
import { Image, Text, View, Pressable } from "react-native";

import { AlertTriangle, MapPin, Clock3, Trash2 } from "lucide-react-native";

import ImageViewing from "react-native-image-viewing";

import ManualSection from "../common/ManualSection";
import ManualStep from "../common/ManualStep";
import ManualTip from "../common/ManualTip";

type Props = {
  expanded: boolean;
  onPress: () => void;
};

export default function AlertList({ expanded, onPress }: Props) {
  const [isImageVisible, setIsImageVisible] = useState(false);

  const alertListImage = require("../../../assets/images/userManual/alerts/alert-list.png");

  return (
    <>
      <ManualSection
        number={3}
        title="ALERT LIST"
        description="Displays the individual alerts and detected events recorded by the system."
        icon={<AlertTriangle size={18} color="#203D70" />}
        expanded={expanded}
        onPress={onPress}
      >
        <View className="mt-5 px-5">
          {/* ============================================== */}
          {/* INTRO */}
          {/* ============================================== */}

          <Text className="mb-4 text-[12px] leading-5 text-slate-600">
            The Alert List displays individual alerts generated by the
            monitoring system. Each alert card provides a quick summary of the
            detected event.
          </Text>

          {/* ============================================== */}
          {/* ACTUAL ALERT LIST SCREENSHOT */}
          {/* ============================================== */}

          <View className="mb-5">
            <View className="mb-2">
              <Text className="text-[13px] font-bold text-slate-800">
                Alert List Preview
              </Text>

              <Text className="mt-0.5 text-[10px] text-slate-500">
                Tap the image to view it in fullscreen
              </Text>
            </View>

            <Pressable
              onPress={() => setIsImageVisible(true)}
              className="overflow-hidden rounded-2xl border border-slate-300 bg-white"
            >
              <View className="relative items-center bg-slate-50 p-2">
                <Image
                  source={alertListImage}
                  resizeMode="contain"
                  style={{
                    width: "100%",
                    height: 430,
                  }}
                />

                {/* Zoom Badge */}
                <View className="absolute bottom-3 right-3 rounded-full bg-slate-900/80 px-3 py-2">
                  <Text className="text-[10px] font-semibold text-white">
                    🔍 Tap to enlarge
                  </Text>
                </View>
              </View>

              {/* IMAGE CAPTION */}
              <View className="border-t border-slate-100 px-4 py-3">
                <Text className="text-center text-xs font-semibold text-slate-700">
                  Alert List
                </Text>

                <Text className="mt-1 text-center text-[10px] text-slate-400">
                  Tap to zoom and inspect the alert cards
                </Text>
              </View>
            </Pressable>
          </View>

          {/* ============================================== */}
          {/* WHAT EACH ALERT CARD SHOWS */}
          {/* ============================================== */}

          <Text className="mb-3 text-[13px] font-bold text-slate-800">
            Information Shown on Alert Cards
          </Text>

          {/* ALERT TYPE */}

          <View className="mb-3 rounded-2xl border border-slate-200 bg-white p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-xl bg-red-50">
                <AlertTriangle size={17} color="#DC2626" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-slate-700">
                  Alert Type
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-500">
                  Identifies the type of event detected by the system, such as a
                  Critical Clog Detected, Moderate Clog Detected, Low Clog
                  Detected, or Water Level Rising.
                </Text>
              </View>
            </View>
          </View>

          {/* LOCATION */}

          <View className="mb-3 rounded-2xl border border-slate-200 bg-white p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-xl bg-blue-50">
                <MapPin size={17} color="#2563EB" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-slate-700">
                  Location
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-500">
                  Shows the barangay or monitored location where the alert was
                  detected.
                </Text>
              </View>
            </View>
          </View>

          {/* SEVERITY */}

          <View className="mb-3 rounded-2xl border border-slate-200 bg-white p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-xl bg-amber-50">
                <AlertTriangle size={17} color="#D97706" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-slate-700">
                  Severity
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-500">
                  Indicates how serious the detected event is. The alert badge
                  helps distinguish different severity levels.
                </Text>
              </View>
            </View>
          </View>

          {/* WASTE TYPE */}

          <View className="mb-3 rounded-2xl border border-slate-200 bg-white p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-xl bg-slate-100">
                <Trash2 size={17} color="#64748B" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-slate-700">
                  Waste Type
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-500">
                  Displays the waste classification associated with the detected
                  clog event when available.
                </Text>
              </View>
            </View>
          </View>

          {/* TIME */}

          <View className="mb-5 rounded-2xl border border-slate-200 bg-white p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-xl bg-slate-100">
                <Clock3 size={17} color="#64748B" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-slate-700">
                  Time Detected
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-500">
                  Shows when the alert was detected or how long ago the event
                  occurred.
                </Text>
              </View>
            </View>
          </View>

          {/* ============================================== */}
          {/* HOW TO VIEW AN ALERT */}
          {/* ============================================== */}

          <Text className="mb-3 text-[13px] font-bold text-slate-800">
            How to View an Alert
          </Text>

          <ManualStep
            number={1}
            text="Review the alert type and severity displayed on the alert card."
          />

          <ManualStep
            number={2}
            text="Check the location, waste type, and time information shown on the card."
          />

          <ManualStep
            number={3}
            text="Tap an alert card to view its detailed information and current monitoring status."
          />

          {/* ============================================== */}
          {/* TIP */}
          {/* ============================================== */}

          <ManualTip>
            Pay attention to alerts with higher severity because they may
            require immediate attention. Selecting an alert opens its detailed
            information.
          </ManualTip>
        </View>
      </ManualSection>

      {/* ============================================== */}
      {/* FULLSCREEN IMAGE VIEWER */}
      {/* ============================================== */}

      <ImageViewing
        images={[
          {
            uri: Image.resolveAssetSource(alertListImage).uri,
          },
        ]}
        imageIndex={0}
        visible={isImageVisible}
        onRequestClose={() => setIsImageVisible(false)}
        presentationStyle="fullScreen"
        backgroundColor="#0F172A"
      />
    </>
  );
}
