import React, { useState } from "react";
import { Image, Text, View, Pressable } from "react-native";
import { Bell, ArrowRight, Info, ZoomIn } from "lucide-react-native";
import ImageViewing from "react-native-image-viewing";

import ManualSection from "../common/ManualSection";
import ManualStep from "../common/ManualStep";
import ManualTip from "../common/ManualTip";

type Props = {
  expanded: boolean;
  onPress: () => void;
};

export default function AlertAccess({ expanded, onPress }: Props) {
  const [isImageVisible, setIsImageVisible] = useState(false);
  const [selectedImage, setSelectedImage] = useState(0);

  const alertAccessImage = require("../../../assets/images/userManual/alerts/alert-access.jpg");

  const alertScreenImage = require("../../../assets/images/userManual/alerts/alert-screen.png");

  const images = [
    {
      uri: Image.resolveAssetSource(alertAccessImage).uri,
    },
    {
      uri: Image.resolveAssetSource(alertScreenImage).uri,
    },
  ];

  const openImage = (index: number) => {
    setSelectedImage(index);
    setIsImageVisible(true);
  };

  return (
    <>
      <ManualSection
        number={1}
        title="HOW TO ACCESS ALERTS"
        description="Access the Alerts screen through the notification bell located at the upper-right portion of the application."
        icon={<Bell size={18} color="#203D70" />}
        expanded={expanded}
        onPress={onPress}
      >
        <View className="mt-5 px-5">
          {/* ================================================= */}
          {/* STEP 1 */}
          {/* ================================================= */}

          <ManualStep
            number={1}
            text="Open the application and on the top right corner is where the notification bell is located."
          />

          {/* ================================================= */}
          {/* MAP SCREENSHOT */}
          {/* ================================================= */}

          <View className="mb-4 mt-1 overflow-hidden rounded-2xl border border-slate-300 bg-white">
            <View className="border-b border-slate-100 px-3 py-2">
              <Text className="text-center text-[10px] font-bold text-slate-700">
                Localized Canal Map
              </Text>
            </View>

            <Pressable onPress={() => openImage(0)} className="bg-slate-50">
              <View className="relative">
                <Image
                  source={alertAccessImage}
                  resizeMode="contain"
                  style={{
                    width: "100%",
                    height: 230,
                  }}
                />

                {/* Zoom Badge */}
                <View className="absolute bottom-2 right-2 rounded-full bg-slate-900/80 px-3 py-2">
                  <View className="flex-row items-center">
                    <ZoomIn size={11} color="#FFFFFF" />

                    <Text className="ml-1 text-[9px] font-semibold text-white">
                      Tap to enlarge
                    </Text>
                  </View>
                </View>
              </View>
            </Pressable>
          </View>

          {/* ================================================= */}
          {/* STEP 2 */}
          {/* ================================================= */}

          <ManualStep
            number={2}
            text="Tap the Notification Bell located at the upper-right portion of the application."
          />

          {/* ================================================= */}
          {/* BELL EXPLANATION */}
          {/* ================================================= */}

          <View className="mb-4 rounded-2xl border border-blue-100 bg-blue-50 p-4">
            <View className="flex-row items-start">
              <View className="mr-3 h-9 w-9 items-center justify-center rounded-full bg-white">
                <Bell size={18} color="#203D70" />
              </View>

              <View className="flex-1">
                <Text className="text-[12px] font-bold text-[#203D70]">
                  Notification Bell
                </Text>

                <Text className="mt-1 text-[10px] leading-4 text-slate-600">
                  The notification bell provides quick access to alerts
                  generated by the monitoring system.
                </Text>
              </View>
            </View>
          </View>

          {/* ================================================= */}
          {/* STEP 3 */}
          {/* ================================================= */}

          <ManualStep
            number={3}
            text="The Alerts screen will be displayed after tapping the notification bell."
          />

          {/* ================================================= */}
          {/* ALERT SCREENSHOT */}
          {/* ================================================= */}

          <View className="mb-4 mt-1 overflow-hidden rounded-2xl border border-slate-300 bg-white">
            <View className="border-b border-slate-100 px-3 py-2">
              <View className="flex-row items-center justify-center">
                <Bell size={12} color="#203D70" />

                <Text className="ml-1.5 text-center text-[10px] font-bold text-slate-700">
                  Alerts
                </Text>
              </View>
            </View>

            <Pressable onPress={() => openImage(1)} className="bg-slate-50">
              <View className="relative">
                <Image
                  source={alertScreenImage}
                  resizeMode="contain"
                  style={{
                    width: "100%",
                    height: 430,
                  }}
                />

                {/* Zoom Badge */}
                <View className="absolute bottom-2 right-2 rounded-full bg-slate-900/80 px-3 py-2">
                  <View className="flex-row items-center">
                    <ZoomIn size={11} color="#FFFFFF" />

                    <Text className="ml-1 text-[9px] font-semibold text-white">
                      Tap to enlarge
                    </Text>
                  </View>
                </View>
              </View>
            </Pressable>
          </View>

          {/* ================================================= */}
          {/* STEP 4 */}
          {/* ================================================= */}

          <ManualStep
            number={4}
            text="Select an alert from the list to view its detailed information."
          />

          {/* ================================================= */}
          {/* ALERT FLOW */}
          {/* ================================================= */}

          <View className="mb-5 rounded-2xl border border-slate-200 bg-white p-4">
            <Text className="mb-3 text-[12px] font-bold text-slate-800">
              Alert Access Flow
            </Text>

            <View className="flex-row items-center justify-between">
              {/* NOTIFICATION */}
              <View className="items-center">
                <View className="h-10 w-10 items-center justify-center rounded-full bg-blue-50">
                  <Bell size={17} color="#203D70" />
                </View>

                <Text className="mt-1.5 text-[9px] font-semibold text-slate-600">
                  Notification
                </Text>
              </View>

              <ArrowRight size={15} color="#94A3B8" />

              {/* ALERTS */}
              <View className="items-center">
                <View className="h-10 w-10 items-center justify-center rounded-full bg-blue-50">
                  <Text className="text-[12px] font-bold text-[#203D70]">
                    A
                  </Text>
                </View>

                <Text className="mt-1.5 text-[9px] font-semibold text-slate-600">
                  Alerts
                </Text>
              </View>

              <ArrowRight size={15} color="#94A3B8" />

              {/* DETAILS */}
              <View className="items-center">
                <View className="h-10 w-10 items-center justify-center rounded-full bg-blue-50">
                  <Info size={17} color="#203D70" />
                </View>

                <Text className="mt-1.5 text-[9px] font-semibold text-slate-600">
                  Details
                </Text>
              </View>
            </View>
          </View>

          {/* ================================================= */}
          {/* TIP */}
          {/* ================================================= */}

          <ManualTip>
            Tap the notification bell whenever you need to check newly generated
            alerts. From the Alerts screen, you can review alert summaries,
            select individual alerts, view detailed information, and apply
            filters.
          </ManualTip>
        </View>
      </ManualSection>

      {/* ========================================= */}
      {/* FULLSCREEN IMAGE VIEWER */}
      {/* ========================================= */}

      <ImageViewing
        images={images}
        imageIndex={selectedImage}
        visible={isImageVisible}
        onRequestClose={() => setIsImageVisible(false)}
        presentationStyle="fullScreen"
        backgroundColor="#0F172A"
      />
    </>
  );
}
