# Generated by Django 5.2.14 on 2026-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Clog', 'Clog'), ('Abnormal_Water_Level', 'Abnormal Water Level')], max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_alerts',
            },
        ),
    ]
