# Generated by Django 5.2.14 on 2026-06-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('clog_events', '0002_initial'),
        ('sensor_nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='node',
            field=models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Clog', 'Clog'), ('Abnormal_Water_Level', 'Abnormal Water Level'), ('Node_Offline', 'Node Offline'), ('Low_Battery', 'Low Battery'), ('Weak_Signal', 'Weak Signal'), ('Sensor_Failure', 'Sensor Failure')], max_length=25),
        ),
        migrations.AlterField(
            model_name='alert',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clog_events.clogevent'),
        ),
    ]
