# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_node_alter_alert_alert_type_alter_alert_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='node',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='user',
            new_name='user_id',
        ),
    ]
