# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_rename_event_alert_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='node_id',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='user_id',
            new_name='user',
        ),
    ]
