# Generated by Django 5.2.14 on 2026-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_rename_event_id_alert_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Overflow_Detected', 'Overflow Detected'), ('Water_Level_Rising', 'Water Level Rising'), ('High_Clog_Index', 'High Clog Index'), ('Node_Offline', 'Node Offline'), ('Low_Battery', 'Low Battery'), ('Weak_Signal', 'Weak Signal'), ('Sensor_Failure', 'Sensor Failure')], max_length=25),
        ),
    ]
