# Generated by Django 5.2.14 on 2026-06-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alert_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.CreateModel(
            name='AlertRead',
            fields=[
                ('read_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='alerts.alert')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_alert_reads',
                'unique_together': {('alert', 'user')},
            },
        ),
    ]
