# Generated by Django 5.2.14 on 2026-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_remove_alert_user_alertread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Water_Level_Rising', 'Water Level Rising'), ('Critical_Clog', 'Critical Clog'), ('Node_Offline', 'Node Offline'), ('Low_Battery', 'Low Battery'), ('Weak_Signal', 'Weak Signal'), ('Sensor_Failure', 'Sensor Failure')], max_length=25),
        ),
    ]
