# Generated by Django 5.2.14 on 2026-06-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_alert_alert_type'),
        ('sensor_nodes', '0004_sensornode_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='health_log',
            field=models.ForeignKey(blank=True, db_column='health_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor_nodes.systemhealthlog'),
        ),
    ]
