# Generated by Django 5.2.14 on 2026-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alert_health_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
