# Generated by Django 5.2.14 on 2026-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alert_alert_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Water_Level_Rising', 'Water Level Rising'), ('Low_Clog_Alert', 'Low Clog Alert'), ('Moderate_Clog_Alert', 'Moderate Clog Alert'), ('Critical_Clog', 'Critical Clog'), ('Node_Offline', 'Node Offline'), ('Low_Battery', 'Low Battery'), ('Weak_Signal', 'Weak Signal'), ('Sensor_Failure', 'Sensor Failure')], max_length=25),
        ),
    ]
