# Generated by Django 5.2.14 on 2026-09-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_alter_alert_alert_type'),
        ('reports', '0020_remove_reportmedia_clog_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='report',
            field=models.ForeignKey(blank=True, db_column='report_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.canalmonitoringreport'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Water_Level_Rising', 'Water Level Rising'), ('Low_Clog_Alert', 'Low Clog Alert'), ('Moderate_Clog_Alert', 'Moderate Clog Alert'), ('Critical_Clog', 'Critical Clog'), ('Node_Offline', 'Node Offline'), ('Low_Battery', 'Low Battery'), ('Weak_Signal', 'Weak Signal'), ('Sensor_Failure', 'Sensor Failure'), ('Report_Submitted', 'Report Submitted')], max_length=25),
        ),
    ]
