# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='barangay',
            new_name='barangay_id',
        ),
    ]
