# Generated by Django 5.2.14 on 2026-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_barangay_user_barangay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='barangay_id',
            new_name='barangay',
        ),
    ]
