# Generated by Django 5.2.14 on 2026-07-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('MENRO', 'MENRO'), ('MENRO_Staff', 'MENRO Staff'), ('Barangay', 'Barangay')], max_length=20),
        ),
    ]
