# Generated by Django 5.2.14 on 2026-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
