# Generated by Django 5.2.14 on 2026-07-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSoundConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('critical_sound', models.CharField(default='preset:alarm', max_length=255)),
                ('warning_sound', models.CharField(default='preset:chime', max_length=255)),
                ('info_sound', models.CharField(default='preset:ping', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_alert_sound_config',
            },
        ),
        migrations.CreateModel(
            name='UploadedAlertSound',
            fields=[
                ('sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='alert_sounds/')),
                ('duration_seconds', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_uploaded_alert_sounds',
            },
        ),
    ]
