# Generated by Django 5.2.14 on 2026-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_sounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsoundconfig',
            name='critical_sound',
            field=models.CharField(default='preset:critical', max_length=255),
        ),
        migrations.AlterField(
            model_name='alertsoundconfig',
            name='info_sound',
            field=models.CharField(default='preset:info', max_length=255),
        ),
        migrations.AlterField(
            model_name='alertsoundconfig',
            name='warning_sound',
            field=models.CharField(default='preset:warning', max_length=255),
        ),
    ]
