# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user',
            new_name='user_id',
        ),
    ]
