# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_rename_user_auditlog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_id',
            new_name='user',
        ),
    ]
