# Generated by Django 5.2.14 on 2026-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
