# Generated by Django 5.2.14 on 2026-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_rename_longtitude_barangay_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=10),
        ),
    ]
