# Generated by Django 5.2.14 on 2026-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0004_seed_barangays'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
