# Generated by Django 5.2.14 on 2026-06-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0005_barangay_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='status',
        ),
    ]
