# Generated by Django 5.2.14 on 2026-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCapture',
            fields=[
                ('capture_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_label', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='training_captures/')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_training_capture',
            },
        ),
    ]
