# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor_nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.FloatField()),
                ('water_flow', models.FloatField()),
                ('reading_status', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode')),
            ],
            options={
                'db_table': 'tbl_sensor_readings',
            },
        ),
    ]
