# Generated by Django 5.2.14 on 2026-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='water_flow_rate',
            field=models.FloatField(blank=True, help_text='Calculated flow rate in m/s from camera analysis', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='water_flow',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Slow', 'Slow'), ('Stagnant', 'Stagnant')], default='Normal', max_length=10),
        ),
    ]
