# Generated by Django 5.2.14 on 2026-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_readings', '0002_sensorreading_water_flow_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='clog_pct',
            field=models.FloatField(blank=True, help_text='Calculated clog percentage base on water level and water flow rate', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='reading_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Overflow', 'Overflow')], default='Normal', max_length=10),
        ),
    ]
