# Generated by Django 5.2.14 on 2026-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_readings', '0003_sensorreading_clog_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='reading_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=10),
        ),
    ]
