# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor_nodes', '0001_initial'),
        ('sensor_readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteClassification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('Recyclable', 'Recyclable'), ('Biodegradable', 'Biodegradable'), ('Residual', 'Residual'), ('Special Waste', 'Special Waste'), ('None', 'None')], max_length=20)),
                ('estimated_volume', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode')),
                ('reading', models.OneToOneField(db_column='reading_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_readings.sensorreading')),
            ],
            options={
                'db_table': 'tbl_waste_classification',
            },
        ),
    ]
