# Generated by Django 5.2.14 on 2026-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_classification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteclassification',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='biodegradable_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='dominant_waste_type',
            field=models.CharField(choices=[('Recyclable', 'Recyclable'), ('Biodegradable', 'Biodegradable'), ('Residual', 'Residual'), ('Special Waste', 'Special Waste'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='none_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='recyclable_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='residual_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='special_waste_pct',
            field=models.FloatField(default=0),
        ),
    ]
