# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_classification', '0002_remove_wasteclassification_waste_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteclassification',
            old_name='node',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='wasteclassification',
            old_name='reading',
            new_name='reading_id',
        ),
    ]
