# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_classification', '0003_rename_node_wasteclassification_node_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteclassification',
            old_name='node_id',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='wasteclassification',
            old_name='reading_id',
            new_name='reading',
        ),
    ]
