# Generated by Django 5.2.14 on 2026-06-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_classification', '0004_rename_node_id_wasteclassification_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteclassification',
            name='is_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='present_waste_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
