# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0002_rename_longtitude_barangay_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalMonthlyReport',
            fields=[
                ('municipal_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_month', models.DateField(unique=True)),
                ('total_recyclables_kg', models.FloatField(default=0)),
                ('total_amount_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_biodegradable_kg', models.FloatField(default=0)),
                ('total_composting_kg', models.FloatField(blank=True, null=True)),
                ('total_residual_waste_kg', models.FloatField(default=0)),
                ('total_special_waste_kg', models.FloatField(blank=True, null=True)),
                ('total_barangays_reported', models.IntegerField(default=0)),
                ('total_clog_events', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=10)),
                ('generated_by', models.ForeignKey(db_column='generated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_municipal_monthly_report',
            },
        ),
        migrations.CreateModel(
            name='BarangayMonthlyReport',
            fields=[
                ('monthly_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_month', models.DateField()),
                ('entry_date', models.DateField()),
                ('recyclables_kg', models.FloatField(default=0)),
                ('amount_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('biodegradable_kg', models.FloatField(default=0)),
                ('composting_kg', models.FloatField(blank=True, null=True)),
                ('residual_waste_kg', models.FloatField(default=0)),
                ('special_waste_kg', models.FloatField(blank=True, null=True)),
                ('clog_events_addressed', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
                ('submitted_by', models.ForeignKey(db_column='submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
                ('municipal_report', models.ForeignKey(blank=True, db_column='municipal_report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.municipalmonthlyreport')),
            ],
            options={
                'db_table': 'tbl_barangay_monthly_report',
                'unique_together': {('barangay', 'report_month')},
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_report', models.ForeignKey(db_column='monthly_report_id', on_delete=django.db.models.deletion.CASCADE, to='reports.barangaymonthlyreport')),
            ],
            options={
                'db_table': 'tbl_report_media',
            },
        ),
    ]
