# Generated by Django 5.2.14 on 2026-06-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0002_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmedia',
            name='clog_event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clog_events.clogevent'),
        ),
        migrations.AlterField(
            model_name='reportmedia',
            name='monthly_report',
            field=models.ForeignKey(blank=True, db_column='monthly_report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.barangaymonthlyreport'),
        ),
    ]
