# Generated by Django 5.2.14 on 2026-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportmedia_clog_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmedia',
            name='file_path',
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_media/'),
        ),
    ]
