# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_rename_longtitude_barangay_longitude'),
        ('reports', '0003_remove_reportmedia_file_path_reportmedia_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangaymonthlyreport',
            old_name='barangay',
            new_name='barangay_id',
        ),
        migrations.RenameField(
            model_name='barangaymonthlyreport',
            old_name='municipal_report',
            new_name='municipal_report_id',
        ),
        migrations.RenameField(
            model_name='reportmedia',
            old_name='clog_event',
            new_name='clog_event_id',
        ),
        migrations.RenameField(
            model_name='reportmedia',
            old_name='monthly_report',
            new_name='monthly_report_id',
        ),
        migrations.AlterUniqueTogether(
            name='barangaymonthlyreport',
            unique_together={('barangay_id', 'report_month')},
        ),
    ]
