# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_barangay_barangaymonthlyreport_barangay_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangaymonthlyreport',
            old_name='barangay_id',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='barangaymonthlyreport',
            old_name='municipal_report_id',
            new_name='municipal_report',
        ),
        migrations.RenameField(
            model_name='reportmedia',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='reportmedia',
            old_name='monthly_report_id',
            new_name='monthly_report',
        ),
    ]
