# Generated by Django 5.2.14 on 2026-06-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_barangay_id_barangaymonthlyreport_barangay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmedia',
            name='media_category',
            field=models.CharField(choices=[('Sensor_Detection', 'Sensor Detection'), ('Before_Clearing', 'Before Clearing'), ('After_Clearing', 'After Clearing')], default='Sensor_Detection', max_length=20),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
