# Generated by Django 5.2.14 on 2026-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportmedia_media_category_reportmedia_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangaymonthlyreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=10),
        ),
    ]
