# Generated by Django 5.2.14 on 2026-07-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_barangaymonthlyreport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangaymonthlyreport',
            old_name='entry_date',
            new_name='clearing_date',
        ),
    ]
