# Generated by Django 5.2.14 on 2026-07-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_entry_date_barangaymonthlyreport_clearing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangaymonthlyreport',
            name='clog_events_addressed',
        ),
    ]
