# Generated by Django 5.2.14 on 2026-07-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_barangaymonthlyreport_clog_events_addressed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmedia',
            old_name='file',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='barangaymonthlyreport',
            name='composting_kg',
        ),
    ]
