# Generated by Django 5.2.14 on 2026-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_file_reportmedia_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
