# Generated by Django 5.2.14 on 2026-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_barangaymonthlyreport_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangaymonthlyreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=10),
        ),
    ]
