# Generated by Django 5.2.14 on 2026-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_barangaymonthlyreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalmonthlyreport',
            name='total_recyclables_kg',
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='bakal_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='bote_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='karton_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='papel_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='plastic_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='municipalmonthlyreport',
            name='total_bakal_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='municipalmonthlyreport',
            name='total_bote_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='municipalmonthlyreport',
            name='total_karton_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='municipalmonthlyreport',
            name='total_papel_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='municipalmonthlyreport',
            name='total_plastic_kg',
            field=models.FloatField(default=0),
        ),
    ]
