# Generated by Django 5.2.14 on 2026-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_municipalmonthlyreport_total_recyclables_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='amount_sold_bakal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='amount_sold_bote_plastic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='barangaymonthlyreport',
            name='amount_sold_papel_karton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
