# Generated by Django 5.2.14 on 2026-08-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_barangaymonthlyreport_amount_sold_bakal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalmonthlyreport',
            name='total_clog_events',
        ),
        migrations.RemoveField(
            model_name='municipalmonthlyreport',
            name='total_composting_kg',
        ),
    ]
