# Generated by Django 5.2.14 on 2026-08-27 11:46

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_municipalmonthlyreport_total_clog_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmedia',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_media_upload_path),
        ),
    ]
