# Generated by Django 5.2.14 on 2026-09-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
        ('clog_events', '0009_clogevent_responded_at'),
        ('reports', '0016_alter_reportmedia_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmedia',
            name='monthly_report',
        ),
        migrations.RemoveField(
            model_name='municipalmonthlyreport',
            name='generated_by',
        ),
        migrations.AlterField(
            model_name='reportmedia',
            name='media_category',
            field=models.CharField(choices=[('Before_Clearing', 'Before Clearing'), ('After_Clearing', 'After Clearing'), ('Additional_Evidence', 'Additional Evidence')], default='Additional_Evidence', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportmedia',
            name='media_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=10),
        ),
        migrations.CreateModel(
            name='CanalMonitoringReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('canal_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nearest_landmark', models.CharField(blank=True, max_length=255)),
                ('date_observed', models.DateTimeField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('water_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10)),
                ('obstruction_coverage', models.CharField(choices=[('Under_25', '<25%'), ('25_50', '25–50%'), ('50_75', '50–75%'), ('Over_75', '>75%')], max_length=10)),
                ('water_flow_condition', models.CharField(choices=[('Normal', 'Normal'), ('Reduced', 'Reduced'), ('Blocked', 'Blocked')], max_length=10)),
                ('waste_plastic_kg', models.FloatField(blank=True, null=True)),
                ('waste_paper_cardboard_kg', models.FloatField(blank=True, null=True)),
                ('waste_glass_kg', models.FloatField(blank=True, null=True)),
                ('waste_organic_kg', models.FloatField(blank=True, null=True)),
                ('waste_metal_kg', models.FloatField(blank=True, null=True)),
                ('waste_foam_kg', models.FloatField(blank=True, null=True)),
                ('waste_other_kg', models.FloatField(blank=True, null=True)),
                ('waste_other_label', models.CharField(blank=True, max_length=100)),
                ('item_plastic_bottle', models.IntegerField(blank=True, null=True)),
                ('item_plastic_bag', models.IntegerField(blank=True, null=True)),
                ('item_food_wrapper', models.IntegerField(blank=True, null=True)),
                ('item_bottle_cap', models.IntegerField(blank=True, null=True)),
                ('item_styrofoam_foam', models.IntegerField(blank=True, null=True)),
                ('item_other', models.IntegerField(blank=True, null=True)),
                ('item_other_label', models.CharField(blank=True, max_length=100)),
                ('assigned_personnel', models.CharField(max_length=150)),
                ('date_responded', models.DateTimeField()),
                ('action_taken', models.TextField()),
                ('waste_collected_amount', models.FloatField(blank=True, null=True)),
                ('waste_collected_unit', models.CharField(choices=[('kg', 'kg'), ('L', 'L'), ('Other', 'Other')], default='kg', max_length=10)),
                ('final_canal_condition', models.CharField(choices=[('Clear', 'Clear'), ('Partially_Clear', 'Partially Clear'), ('Still_Obstructed', 'Still Obstructed')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
                ('clog_event', models.ForeignKey(blank=True, db_column='clog_event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clog_events.clogevent')),
                ('reported_by', models.ForeignKey(db_column='reported_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canal_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_canal_monitoring_reports',
            },
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='report',
            field=models.ForeignKey(blank=True, db_column='report_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.canalmonitoringreport'),
        ),
        migrations.DeleteModel(
            name='BarangayMonthlyReport',
        ),
        migrations.DeleteModel(
            name='MunicipalMonthlyReport',
        ),
    ]
