# Generated by Django 5.2.14 on 2026-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_remove_reportmedia_monthly_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='assigned_personnel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='canal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='date_observed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='date_responded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='final_canal_condition',
            field=models.CharField(blank=True, choices=[('Clear', 'Clear'), ('Partially_Clear', 'Partially Clear'), ('Still_Obstructed', 'Still Obstructed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='obstruction_coverage',
            field=models.CharField(blank=True, choices=[('Under_25', '<25%'), ('25_50', '25–50%'), ('50_75', '50–75%'), ('Over_75', '>75%')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='severity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='water_flow_condition',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Reduced', 'Reduced'), ('Blocked', 'Blocked')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canalmonitoringreport',
            name='water_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
    ]
