# Generated by Django 5.2.14 on 2026-09-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_canalmonitoringreport_is_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_bottle_cap',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_food_wrapper',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_other',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_other_label',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_plastic_bag',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_plastic_bottle',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='item_styrofoam_foam',
        ),
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='waste_ewaste_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='waste_food_wrapper_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='waste_textile_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
