# Generated by Django 5.2.14 on 2026-09-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_remove_canalmonitoringreport_item_bottle_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmedia',
            name='clog_event_id',
        ),
    ]
