# Generated by Django 5.2.14 on 2026-10-03 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_canalmonitoringreport_signatory_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='purok',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
