# Generated by Django 5.2.14 on 2026-10-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_canalmonitoringreport_purok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canalmonitoringreport',
            old_name='obstruction_coverage',
            new_name='overall_obstruction_coverage',
        ),
        migrations.RenameField(
            model_name='canalmonitoringreport',
            old_name='water_flow_condition',
            new_name='overall_water_flow_condition',
        ),
        migrations.RenameField(
            model_name='canalmonitoringreport',
            old_name='water_level',
            new_name='overall_water_level',
        ),
    ]
