# Generated by Django 5.2.14 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_rename_obstruction_coverage_canalmonitoringreport_overall_obstruction_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmonitoringreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
