# Generated by Django 5.2.14 on 2026-10-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_backfill_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='canal_name',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='final_canal_condition',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='canalmonitoringreport',
            name='nearest_landmark',
        ),
    ]
