"use client"

import { useEffect, useState } from "react"
import IntroScreen from "./components/IntroScreen"
import ManualIntro from "./components/ManualIntro"
import SearchBar from "./components/SearchBar"
import TopicTabs from "./components/TopicTabs"
import StepsList, { ManualStep } from "./components/StepList"
import StepDetail from "./components/StepDetails"

interface ManualTopic {
  id: string
  label: string
  steps: ManualStep[]
}

// Topics restricted to MENRO (full officer) only — hidden for MENRO_Staff
const RESTRICTED_TOPIC_IDS = ["resource", "history", "hotspots", "dashboard"]

// Each topic is its own manual page with its own step-by-step content.
// Swap the `steps` arrays for real content (or an API fetch) later —
// nothing else in this file needs to change.
const TOPICS: ManualTopic[] = [

  {
    id: "map",
    label: "Regional Map",
    steps: [
      {
        id: "map-overview",
        label: "Overview of Regional Map",
        description: "The Dashboard provides a centralized overview of the canal monitoring system, the canal network map, live waste classification, live alerts, and reporting progress.",
        whyItMatters: "Placeholder — explain why the regional map matters.",
        extraSections: [
          {
            label: "Canal Network Map",
            description: "This shows the entire map of Rosario La Union. Where you click a sensor node on the map to view its current status and reveal additional information about the selected node. The information displayed may include the node name, location, risk level, clog rate, and water level.",
          },
          {
            label: "Zoom In | Zoom Out",
            description: "Click the Plus (+) button to zoom in on the map. This allows users to view the canal network and sensor locations in greater detail and at a closer scale. \nClick the Minus (−) button to zoom out of the map. This allows users to view a wider area of the canal network and surrounding locations at a larger scale.",
          },
           {
            label: "Legend",
            description: "Live Risk Level legend uses color-coded labels to help users quickly identify the condition and priority level of each monitored location.",
          },
        ]
      },
      {
        id: "live-alerts",
        label: "Live Alerts",
        description: "This shows the Live Alerts section displays real-time notifications generated by the canal monitoring system. It allows users to quickly identify potential hazards, sensor issues, and changes in canal conditions that may require attention \n Red – Critical Clog",
        whyItMatters: "Placeholder — explain why map layers matter."
        
      },
      {
        id: "waste-classification",
        label: "Waste Classifications",
        description: "This shows the Live Alerts section displays real-time notifications generated by the canal monitoring system. It allows users to quickly identify potential hazards, sensor issues, and changes in canal conditions that may require attention \n Red – Critical Clog",
        whyItMatters: "Placeholder — explain why map layers matter."
        
      },
    ],
  },
  {
    id: "hotspots",
    label: "Canal Hotspots",
    steps: [
      {
        id: "hotspot-list",
        label: "Canal Hotspot Overview",
        description: "Provides an overview of designated canal hotspots across different barangays, including their total number, availability, and occupancy status.",
        whyItMatters: "Placeholder — explain why viewing hotspots matters.",
        
      },
      {
        id: "hotspot-manage",
        label: "Hotspot Table",
        description: "Provides an overview of designated canal hotspots across different barangays, including their total number, availability, and occupancy status.",
        whyItMatters: "Placeholder — explain why managing hotspots matters.",
        extraSections: [
          {
            label: "View Button",
            description: "Clicking the View button expands the row to display the list of hotspots registered under that barangay, showing each hotspot's name, shape, and status.",
          },
          {
            label: "View on Maps",
            description: "Clicking 'View on map' opens a modal displaying the hotspot's exact location on an interactive map, along with its coordinates and a status legend (Available/Occupied).",
          },
          {
            label: "Zoom in | Zoom out",
            description: "Users can zoom in/out, close the modal, or click 'Open in Maps' to view the location in an external maps application.",
          },
        ]
        
      },
      {
        id: "hotspot-manage-three-button",
        label: "Three-dot Menu",
        description: "Clicking the three-dot (⋮) menu opens a dropdown with two options: Edit, to modify the hotspot's details, and Remove, to delete the hotspot from the list.",
        whyItMatters: "Placeholder — explain why managing hotspots matters.",
        extraSections: [
          {
            label: "Remove Button",
            description: "Clicking Remove opens a confirmation dialog warning that the action cannot be undone. Clicking Remove permanently deletes the hotspot, while clicking Cancel closes the dialog without making any changes.",
          },
          {
            label: "Edit Button",
            description: "Clicking Edit opens a form pre-filled with the hotspot's existing details. Hotspot Information (barangay, name, description), Canal Properties (width, shape, depth, sensor height), and Geographic Location (map pin with latitude/longitude). Allowing the user to update any field. Changes are saved by clicking Save Changes, or discarded by clicking Cancel.",
          },
          {
            label: "Confirmation Modal - Save",
            description: "After clicking Save Changes, a Confirm Changes dialog appears asking the user to verify the update. Clicking Confirm Changes finalizes and saves the updates, while clicking Keep Editing returns to the edit form without saving.",
          },
          {
            label: "Confirmation Modal - Cancel",
            description: "Clicking Cancel while there are unsaved changes triggers a Cancel Changes confirmation dialog, warning the user that unsaved changes will be lost. Clicking Yes, Cancel discards the changes and closes the form, while clicking Keep Editing returns to the edit form without discarding anything.",
          },
        ]
      },
      {
        id: "hotspot-manage-add-button",
        label: "Add Button",
        description: "Clicking the “Add Hotspot” button opens the hotspot registration form, where users can enter the hotspot’s name and description, specify the canal properties such as width, shape, depth, and sensor height, and select its geographic location on the map. The hotspot coordinates are automatically recorded when the user clicks within the highlighted barangay boundary.",
        whyItMatters: "Placeholder — explain why managing hotspots matters.",
        extraSections: [
          {
            label: "Confirmation Modal - Save",
            description: "Clicking the “Add Hotspot” button will display a confirmation modal asking the user to confirm the registration of the new hotspot. This ensures that all entered information is reviewed and confirmed before the hotspot is added to the system.",
          },
          {
            label: "Confirmation Modal - Cancel",
            description: "Clicking the “Cancel” button will display a confirmation modal asking the user to confirm whether they want to cancel the hotspot registration. This ensures that the user does not accidentally discard the information entered for the new hotspot.",
          },
        ]
      }
    ],
  },
  {
    id: "alerts",
    label: "Alerts",
    steps: [
      {
        id: "alert-notif-overview",
        label: "Alert Notification Overview",
        description: "This provides a centralized view of system notifications and detected events from sensor nodes. Users can search notifications, filter alerts by barangay and date, and select specific alert types such as Water Level Rising, Low/Moderate/Critical Clog, Node Offline, Low Battery, Weak Signal, and Sensor Failure to quickly identify and review relevant alerts.",
        whyItMatters: "Placeholder — explain why live alerts matter.",
        
      },
      {
        id: "alert-notif",
        label: "Alert Notification",
        description: "Clicking an alert opens the Alert Details Panel, where users can view important information about the reported incident and its location. The panel provides details such as the alert severity, estimated waste volume, water level, flow rate, and waste classification to help users understand the condition and respond accordingly.",
        whyItMatters: "Placeholder — explain why alert history matters.",
        
      },
    ],
  },
  {
    id: "analytics",
    label: "Waste Analytics",
    steps: [
      {
        id: "waste-summary",
        label: "Waste Analytics Overview",
        description: "Records waste detected in canal hotspots, showing summary metrics such Total Classifications, Biodegradable, Recyclable, and Residual/Others, along with a table listing each classification's ID, Dominant Waste Type, Timestamp, Node, Location, Reading ID, and Confidence level. You can use the Search waste classification bar or the All Barangay, All Waste, and All Nodes dropdowns (individually or combined) to filter results. Selecting a record displays its full details in the panel on the right, and the Export PDF button lets you download the classification log.",
        whyItMatters: "Placeholder — explain why waste analytics matter.",
        
      },
    ],
  },
  {
    id: "resource",
    label: "Resource Optimization",
    steps: [
      {
        id: "resource-summary",
        label: "Resource Optimization Summary",
        description: "This is the guide on how to use Resource Optimization.",
        whyItMatters: "Placeholder — explain why resource optimization matters.",
        
      },
    ],
  },
  {
    id: "history",
    label: "Compiled Barangay Reports",
    steps: [
      {
        id: "barangay-summary-overview",
        label: "Municipal Reports Overview",
        description: "The Municipal Reports page provides a consolidated view of waste management reports compiled at the municipal level, allowing users to search, filter by month, and review or export verified reports.",
        whyItMatters: "Placeholder — explain why barangay reports matter.",
         extraSections: [
          {
            label: "Search & Filters",
            description: "The search bar lets users look up specific reports using ID and Name, while the month dropdown filter narrows the list to reports from a selected month."
          },
          {
            label: "Summary Cards",
            description: "These cards show quick-glance totals across all compiled reports, including the total number of municipal reports, and the total recyclable, biodegradable, and residual/other waste collected in kilograms.",
          },
          {
            label: "Report Table",
            description: "his table lists individual municipal reports, showing the report ID, the date (month/year) it covers, who verified it.",
          },
        ]
      },
      {
        id: "barangay-search",
        label: "Report View Button",
        description: "Clicking View button on a report opens the full Municipal Report page for the selected month. This report displays a detailed table breaking down waste data per barangay—covering Recyclables (Bote, Bakal, Papel, Plastic, Karton), Amount Sold, Biodegradable Waste, Residual Waste, and Special Waste. Users can click the back arrow to return to the Municipal Reports list, or click Export PDF to download the report.",
        whyItMatters: "Placeholder — explain why barangay reports matter.",
        
      },{
        id: "barangay-cards",
        label: "Export Button",
        description: "Clicking Export PDF button will trigger a confirmation modal, asking the user to verify that they want to export the compiled MRF report for the selected month. Clicking Export in the modal proceeds with generating and downloading the PDF, while clicking Cancel closes the modal without exporting.",
        whyItMatters: "Placeholder — explain why barangay reports matter.",
        
      },
    ],
  },
]

const SEEN_INTRO_KEY = "agos-manual-intro-seen"

export default function UserManual() {
  const [showIntro, setShowIntro] = useState(false)
  const [checkedStorage, setCheckedStorage] = useState(false)
  const [userRole, setUserRole] = useState<string | null>(null)

  const [search, setSearch] = useState("")
  const [filter, setFilter] = useState("all")
  const [activeTopicId, setActiveTopicId] = useState(TOPICS[0].id)
  const [activeStepId, setActiveStepId] = useState(TOPICS[0].steps[0].id)

  const [visitedByTopic, setVisitedByTopic] = useState<Record<string, string[]>>({
    [TOPICS[0].id]: [TOPICS[0].steps[0].id],
  })

  useEffect(() => {
    const seen = localStorage.getItem(SEEN_INTRO_KEY)
    setShowIntro(!seen)

    const userRaw = localStorage.getItem("user")
    if (userRaw) {
      try {
        const parsed = JSON.parse(userRaw)
        setUserRole(parsed.user_role ?? null)
      } catch {
        setUserRole(null)
      }
    }

    setCheckedStorage(true)
  }, [])

  const dismissIntro = () => {
    localStorage.setItem(SEEN_INTRO_KEY, "true")
    setShowIntro(false)
  }

  // MENRO_Staff doesn't get Resource Optimization or History
  const visibleTopics =
    userRole === "MENRO_Staff"
      ? TOPICS.filter((t) => !RESTRICTED_TOPIC_IDS.includes(t.id))
      : TOPICS

  const activeTopic =
    visibleTopics.find((t) => t.id === activeTopicId) ?? visibleTopics[0]
  const activeStepIndex = activeTopic.steps.findIndex((s) => s.id === activeStepId)
  const activeStep = activeTopic.steps[activeStepIndex] ?? activeTopic.steps[0]
  const visitedStepIds = visitedByTopic[activeTopic.id] ?? []

  const filteredTopics = visibleTopics.filter((t) =>
    t.label.toLowerCase().includes(search.toLowerCase())
  )

  const markVisited = (topicId: string, stepId: string) => {
    setVisitedByTopic((prev) => {
      const current = prev[topicId] ?? []
      if (current.includes(stepId)) return prev
      return { ...prev, [topicId]: [...current, stepId] }
    })
  }

  const goToStepId = (topicId: string, stepId: string) => {
    setActiveTopicId(topicId)
    setActiveStepId(stepId)
    markVisited(topicId, stepId)
  }

  const selectTopic = (topicId: string) => {
    const topic = visibleTopics.find((t) => t.id === topicId)
    if (!topic) return
    goToStepId(topicId, topic.steps[0].id)
  }

  const selectStep = (stepId: string) => {
    goToStepId(activeTopic.id, stepId)
  }

  const goToStep = (offset: number) => {
    const nextIndex = activeStepIndex + offset
    if (nextIndex >= 0 && nextIndex < activeTopic.steps.length) {
      goToStepId(activeTopic.id, activeTopic.steps[nextIndex].id)
    }
  }

  if (!checkedStorage) return null

  if (showIntro) {
    return (
      <div className="max-w-5xl mx-auto py-8 px-4">
        <IntroScreen onGetStarted={dismissIntro} />
      </div>
    )
  }

  return (
    <div className="max-w-20xl mx-auto py-2 px-1">
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <ManualIntro />
        <SearchBar
          value={search}
          onChange={setSearch}
          filter={filter}
          onFilterChange={setFilter}
          filterOptions={visibleTopics.map((t) => t.label)}
        />
        <TopicTabs
          topics={filteredTopics}
          activeTopic={activeTopic.id}
          onSelect={selectTopic}
        />

        <div className="flex">
          <StepsList
            title={activeTopic.label}
            description={`Below is the guide on how to use the ${activeTopic.label}.`}
            steps={activeTopic.steps}
            activeStepId={activeStep.id}
            visitedStepIds={visitedStepIds}
            onSelect={selectStep}
          />
          <StepDetail
            stepIndex={activeStepIndex}
            totalSteps={activeTopic.steps.length}
            title={activeStep.label}
            description={activeStep.description}
            whyItMatters={activeStep.whyItMatters}
            extraSections={activeStep.extraSections}
            onPrevious={() => goToStep(-1)}
            onNext={() => goToStep(1)}
            hasPrevious={activeStepIndex > 0}
            hasNext={activeStepIndex < activeTopic.steps.length - 1}
          />
        </div>
      </div>
    </div>
  )
}