# Generated by Django 5.2.14 on 2026-07-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0006_remove_barangay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm_hr', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('None', 'None'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red')], default='None', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_condition', to='barangay.barangay')),
            ],
            options={
                'db_table': 'tbl_rainfall_conditions',
            },
        ),
    ]
