# Generated by Django 5.2.14 on 2026-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('None', 'None'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Unknown', 'Unknown')], max_length=10, unique=True)),
                ('warning_pct', models.FloatField(help_text='Water level % of canal_depth that triggers a Warning classification.')),
                ('critical_pct', models.FloatField(help_text='Water level % of canal_depth that triggers a Critical classification.')),
            ],
            options={
                'db_table': 'tbl_alert_thresholds',
            },
        ),
    ]
