# Generated by Django 5.2.14 on 2026-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0003_seed_alert_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='reading_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Recommended seconds between sensor readings for this rainfall condition.'),
        ),
    ]
