# Generated by Django 5.2.14 on 2026-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0005_seed_reading_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='clear_streak_count',
            field=models.PositiveIntegerField(default=5, help_text='Consecutive confirmed-clear readings (clog_pct < 30) required to auto-clear an open ClogEvent.'),
        ),
    ]
