# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0002_rename_longtitude_barangay_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClogEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('Detected', 'Detected'), ('Responded', 'Responded'), ('Cleared', 'Cleared'), ('Verified', 'Verified')], default='Detected', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(db_column='barangay_id', on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
            ],
            options={
                'db_table': 'tbl_clog_events',
            },
        ),
    ]
