# Generated by Django 5.2.14 on 2026-05-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clog_events', '0001_initial'),
        ('sensor_nodes', '0001_initial'),
        ('waste_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogevent',
            name='classification',
            field=models.OneToOneField(blank=True, db_column='classification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_classification.wasteclassification'),
        ),
        migrations.AddField(
            model_name='clogevent',
            name='node',
            field=models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='sensor_nodes.sensornode'),
        ),
    ]
