# Generated by Django 5.2.14 on 2026-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clogevent',
            old_name='barangay',
            new_name='barangay_id',
        ),
        migrations.RenameField(
            model_name='clogevent',
            old_name='classification',
            new_name='classification_id',
        ),
        migrations.RenameField(
            model_name='clogevent',
            old_name='node',
            new_name='node_id',
        ),
    ]
