# Generated by Django 5.2.14 on 2026-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0003_rename_barangay_clogevent_barangay_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clogevent',
            old_name='barangay_id',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='clogevent',
            old_name='classification_id',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='clogevent',
            old_name='node_id',
            new_name='node',
        ),
    ]
