# Generated by Django on 2026-06-17 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0004_rename_barangay_id_clogevent_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogevent',
            name='cleared_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                db_column='cleared_by'
            ),
        ),
    ]
