# Generated by Django 5.2.14 on 2026-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0005_add_cleared_by_to_clog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogevent',
            name='first_severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clogevent',
            name='peak_severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
    ]
