# Generated by Django 5.2.14 on 2026-07-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0006_clogevent_first_severity_clogevent_peak_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogevent',
            name='clear_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
