# Generated by Django 5.2.14 on 2026-08-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clog_events', '0008_clogevent_responded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogevent',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
